/**
 * The master product catalogue used to generate store snapshots.
 *
 * These are invented products for a fictional company. No real customer,
 * merchant or transaction data appears anywhere in this seed — see
 * docs/demo-mode.md.
 */

export interface SeedProduct {
  sku: string;
  name: string;
  brand: 'Acme Home' | 'Acme Field' | 'Acme Studio';
  category: string;
  subCategory: string;
  /** Base price in the master store's currency (GBP). */
  basePriceGbp: number;
  costRatio: number;
  weightKg: number;
  productType: 'physical' | 'digital';
  seoTitle: string;
  seoDescription: string;
  customFields: { name: string; value: string }[];
}

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    sku: 'AH-KETTLE-1000',
    name: 'Meridian 1.7L Temperature-Control Kettle',
    brand: 'Acme Home',
    category: 'Kitchen',
    subCategory: 'Small Appliances',
    basePriceGbp: 89.0,
    costRatio: 0.42,
    weightKg: 1.4,
    productType: 'physical',
    seoTitle: 'Meridian Temperature-Control Kettle | Acme Home',
    seoDescription:
      'Brew at exactly the right temperature with six presets, a brushed stainless body and a 40-minute keep-warm hold.',
    customFields: [
      { name: 'Warranty', value: '3 years' },
      { name: 'Material', value: 'Brushed stainless steel' },
    ],
  },
  {
    sku: 'AH-TOASTER-220',
    name: 'Meridian Two-Slice Toaster',
    brand: 'Acme Home',
    category: 'Kitchen',
    subCategory: 'Small Appliances',
    basePriceGbp: 64.0,
    costRatio: 0.4,
    weightKg: 1.9,
    productType: 'physical',
    seoTitle: 'Meridian Two-Slice Toaster | Acme Home',
    seoDescription:
      'Extra-wide slots, seven browning levels and a removable crumb tray, finished to match the Meridian range.',
    customFields: [{ name: 'Warranty', value: '3 years' }],
  },
  {
    sku: 'AH-COFFEE-450',
    name: 'Meridian Burr Coffee Grinder',
    brand: 'Acme Home',
    category: 'Kitchen',
    subCategory: 'Coffee',
    basePriceGbp: 129.0,
    costRatio: 0.38,
    weightKg: 2.6,
    productType: 'physical',
    seoTitle: 'Meridian Burr Coffee Grinder | Acme Home',
    seoDescription:
      'Forty grind settings from espresso to French press, with a static-reducing catch cup.',
    customFields: [
      { name: 'Warranty', value: '3 years' },
      { name: 'Grind settings', value: '40' },
    ],
  },
  {
    sku: 'AH-PAN-28CM',
    name: 'Forge 28cm Tri-Ply Frying Pan',
    brand: 'Acme Home',
    category: 'Kitchen',
    subCategory: 'Cookware',
    basePriceGbp: 72.0,
    costRatio: 0.36,
    weightKg: 1.5,
    productType: 'physical',
    seoTitle: 'Forge 28cm Tri-Ply Frying Pan | Acme Home',
    seoDescription: 'Tri-ply stainless construction with an aluminium core for even heat across induction, gas and electric.',
    customFields: [{ name: 'Induction safe', value: 'Yes' }],
  },
  {
    sku: 'AH-KNIFE-SET8',
    name: 'Forge Eight-Piece Knife Block',
    brand: 'Acme Home',
    category: 'Kitchen',
    subCategory: 'Cutlery',
    basePriceGbp: 185.0,
    costRatio: 0.34,
    weightKg: 4.2,
    productType: 'physical',
    seoTitle: 'Forge Eight-Piece Knife Block | Acme Home',
    seoDescription: 'German steel blades, full-tang construction and a solid oak block.',
    customFields: [{ name: 'Blade steel', value: 'X50CrMoV15' }],
  },
  {
    sku: 'AH-THROW-WOOL',
    name: 'Harbour Lambswool Throw',
    brand: 'Acme Home',
    category: 'Living',
    subCategory: 'Soft Furnishings',
    basePriceGbp: 95.0,
    costRatio: 0.44,
    weightKg: 1.1,
    productType: 'physical',
    seoTitle: 'Harbour Lambswool Throw | Acme Home',
    seoDescription: 'Woven in the British Isles from pure lambswool, finished with a hand-knotted fringe.',
    customFields: [{ name: 'Origin', value: 'Woven in the United Kingdom' }],
  },
  {
    sku: 'AH-LAMP-ARC',
    name: 'Halston Arc Floor Lamp',
    brand: 'Acme Home',
    category: 'Living',
    subCategory: 'Lighting',
    basePriceGbp: 249.0,
    costRatio: 0.4,
    weightKg: 8.5,
    productType: 'physical',
    seoTitle: 'Halston Arc Floor Lamp | Acme Home',
    seoDescription: 'A marble-based arc lamp with a brushed brass stem and dimmable warm-white output.',
    customFields: [{ name: 'Bulb', value: 'E27, not included' }],
  },
  {
    sku: 'AH-RUG-200300',
    name: 'Cotswold Hand-Loomed Rug 200×300',
    brand: 'Acme Home',
    category: 'Living',
    subCategory: 'Rugs',
    basePriceGbp: 420.0,
    costRatio: 0.45,
    weightKg: 18,
    productType: 'physical',
    seoTitle: 'Cotswold Hand-Loomed Rug | Acme Home',
    seoDescription: 'Hand-loomed wool pile in a muted heather palette, sized for a generous living room.',
    customFields: [{ name: 'Pile', value: '100% wool' }],
  },
  {
    sku: 'AF-JACKET-3L',
    name: 'Ridgeline Three-Layer Shell Jacket',
    brand: 'Acme Field',
    category: 'Outdoor',
    subCategory: 'Outerwear',
    basePriceGbp: 320.0,
    costRatio: 0.38,
    weightKg: 0.6,
    productType: 'physical',
    seoTitle: 'Ridgeline Three-Layer Shell Jacket | Acme Field',
    seoDescription: 'A fully taped three-layer shell with pit zips, a helmet-compatible hood and a 20k/20k membrane.',
    customFields: [
      { name: 'Waterproof rating', value: '20,000mm' },
      { name: 'Breathability', value: '20,000g/m²/24h' },
    ],
  },
  {
    sku: 'AF-BOOT-TRAIL',
    name: 'Ridgeline Trail Boot',
    brand: 'Acme Field',
    category: 'Outdoor',
    subCategory: 'Footwear',
    basePriceGbp: 175.0,
    costRatio: 0.36,
    weightKg: 1.2,
    productType: 'physical',
    seoTitle: 'Ridgeline Trail Boot | Acme Field',
    seoDescription: 'A mid-height waterproof boot with a Vibram outsole and a supportive nylon shank.',
    customFields: [{ name: 'Outsole', value: 'Vibram Megagrip' }],
  },
  {
    sku: 'AF-PACK-45L',
    name: 'Summit 45L Trekking Pack',
    brand: 'Acme Field',
    category: 'Outdoor',
    subCategory: 'Packs',
    basePriceGbp: 165.0,
    costRatio: 0.37,
    weightKg: 1.5,
    productType: 'physical',
    seoTitle: 'Summit 45L Trekking Pack | Acme Field',
    seoDescription: 'An adjustable-back trekking pack with a floating lid, hip-belt pockets and a rain cover.',
    customFields: [{ name: 'Volume', value: '45 litres' }],
  },
  {
    sku: 'AF-TENT-2P',
    name: 'Summit Two-Person Backpacking Tent',
    brand: 'Acme Field',
    category: 'Outdoor',
    subCategory: 'Shelter',
    basePriceGbp: 395.0,
    costRatio: 0.41,
    weightKg: 2.1,
    productType: 'physical',
    seoTitle: 'Summit Two-Person Backpacking Tent | Acme Field',
    seoDescription: 'A freestanding two-person tent with dual vestibules and a 3,000mm hydrostatic-head fly.',
    customFields: [{ name: 'Packed weight', value: '2.1kg' }],
  },
  {
    sku: 'AF-STOVE-TI',
    name: 'Summit Titanium Camp Stove',
    brand: 'Acme Field',
    category: 'Outdoor',
    subCategory: 'Cooking',
    basePriceGbp: 78.0,
    costRatio: 0.35,
    weightKg: 0.1,
    productType: 'physical',
    seoTitle: 'Summit Titanium Camp Stove | Acme Field',
    seoDescription: 'A 45g titanium burner with a piezo igniter and a wind-resistant flame ring.',
    customFields: [{ name: 'Weight', value: '45g' }],
  },
  {
    sku: 'AF-GLOVE-WIN',
    name: 'Ridgeline Insulated Glove',
    brand: 'Acme Field',
    category: 'Outdoor',
    subCategory: 'Accessories',
    basePriceGbp: 58.0,
    costRatio: 0.33,
    weightKg: 0.2,
    productType: 'physical',
    seoTitle: 'Ridgeline Insulated Glove | Acme Field',
    seoDescription: 'A waterproof insulated glove with a goat-leather palm and touchscreen-compatible fingertips.',
    customFields: [{ name: 'Insulation', value: 'PrimaLoft Gold' }],
  },
  {
    sku: 'AS-DESK-160',
    name: 'Atelier 160cm Sit-Stand Desk',
    brand: 'Acme Studio',
    category: 'Workspace',
    subCategory: 'Desks',
    basePriceGbp: 649.0,
    costRatio: 0.46,
    weightKg: 42,
    productType: 'physical',
    seoTitle: 'Atelier 160cm Sit-Stand Desk | Acme Studio',
    seoDescription: 'A dual-motor sit-stand desk with a solid oak top, cable tray and four memory presets.',
    customFields: [
      { name: 'Height range', value: '62–128cm' },
      { name: 'Assembly', value: 'Two-person, 30 minutes' },
    ],
  },
  {
    sku: 'AS-CHAIR-ERG',
    name: 'Atelier Ergonomic Task Chair',
    brand: 'Acme Studio',
    category: 'Workspace',
    subCategory: 'Seating',
    basePriceGbp: 529.0,
    costRatio: 0.44,
    weightKg: 19,
    productType: 'physical',
    seoTitle: 'Atelier Ergonomic Task Chair | Acme Studio',
    seoDescription: 'Adjustable lumbar support, a breathable mesh back and 4D armrests, rated for twelve-hour use.',
    customFields: [{ name: 'Warranty', value: '10 years' }],
  },
  {
    sku: 'AS-LAMP-TASK',
    name: 'Atelier LED Task Lamp',
    brand: 'Acme Studio',
    category: 'Workspace',
    subCategory: 'Lighting',
    basePriceGbp: 139.0,
    costRatio: 0.4,
    weightKg: 2.3,
    productType: 'physical',
    seoTitle: 'Atelier LED Task Lamp | Acme Studio',
    seoDescription: 'A wide-throw LED task lamp with stepless dimming and adjustable colour temperature.',
    customFields: [{ name: 'Colour temperature', value: '2700–6500K' }],
  },
  {
    sku: 'AS-MONITOR-ARM',
    name: 'Atelier Single Monitor Arm',
    brand: 'Acme Studio',
    category: 'Workspace',
    subCategory: 'Accessories',
    basePriceGbp: 119.0,
    costRatio: 0.35,
    weightKg: 3.1,
    productType: 'physical',
    seoTitle: 'Atelier Single Monitor Arm | Acme Studio',
    seoDescription: 'A gas-spring monitor arm supporting displays up to 32 inches and 9kg.',
    customFields: [{ name: 'VESA', value: '75×75 and 100×100' }],
  },
  {
    sku: 'AS-SHELF-OAK',
    name: 'Atelier Oak Wall Shelf',
    brand: 'Acme Studio',
    category: 'Workspace',
    subCategory: 'Storage',
    basePriceGbp: 88.0,
    costRatio: 0.42,
    weightKg: 5.4,
    productType: 'physical',
    seoTitle: 'Atelier Oak Wall Shelf | Acme Studio',
    seoDescription: 'A solid oak floating shelf with a concealed steel bracket, finished in hard-wax oil.',
    customFields: [{ name: 'Length', value: '90cm' }],
  },
  {
    sku: 'AS-MAT-DESK',
    name: 'Atelier Leather Desk Mat',
    brand: 'Acme Studio',
    category: 'Workspace',
    subCategory: 'Accessories',
    basePriceGbp: 74.0,
    costRatio: 0.38,
    weightKg: 0.8,
    productType: 'physical',
    seoTitle: 'Atelier Leather Desk Mat | Acme Studio',
    seoDescription: 'A full-grain leather desk mat with a wool-felt underside, sized for a full keyboard and mouse.',
    customFields: [{ name: 'Size', value: '90 × 43cm' }],
  },
  {
    sku: 'AH-CARE-GUIDE',
    name: 'Acme Home Care & Maintenance Guide',
    brand: 'Acme Home',
    category: 'Services',
    subCategory: 'Digital',
    basePriceGbp: 0.0,
    costRatio: 0,
    weightKg: 0,
    productType: 'digital',
    seoTitle: 'Care & Maintenance Guide | Acme Home',
    seoDescription: 'A downloadable guide covering the care of every product in the Acme Home range.',
    customFields: [{ name: 'Format', value: 'PDF, 24 pages' }],
  },
  {
    sku: 'AF-REPAIR-KIT',
    name: 'Ridgeline Field Repair Kit',
    brand: 'Acme Field',
    category: 'Outdoor',
    subCategory: 'Accessories',
    basePriceGbp: 32.0,
    costRatio: 0.3,
    weightKg: 0.15,
    productType: 'physical',
    seoTitle: 'Ridgeline Field Repair Kit | Acme Field',
    seoDescription: 'Patches, seam sealer, a zip slider and cord locks in a pocketable pouch.',
    customFields: [{ name: 'Contents', value: '11 pieces' }],
  },
  {
    sku: 'AH-BOARD-END',
    name: 'Forge End-Grain Chopping Board',
    brand: 'Acme Home',
    category: 'Kitchen',
    subCategory: 'Cookware',
    basePriceGbp: 110.0,
    costRatio: 0.43,
    weightKg: 4.8,
    productType: 'physical',
    seoTitle: 'Forge End-Grain Chopping Board | Acme Home',
    seoDescription: 'An end-grain maple board that is kinder to blades, with recessed handholds and a juice groove.',
    customFields: [{ name: 'Timber', value: 'FSC-certified maple' }],
  },
  {
    sku: 'AS-CABLE-MGMT',
    name: 'Atelier Cable Management Kit',
    brand: 'Acme Studio',
    category: 'Workspace',
    subCategory: 'Accessories',
    basePriceGbp: 42.0,
    costRatio: 0.32,
    weightKg: 0.9,
    productType: 'physical',
    seoTitle: 'Atelier Cable Management Kit | Acme Studio',
    seoDescription: 'A tray, sleeve, clips and adhesive channels to keep a sit-stand desk tidy through its full travel.',
    customFields: [{ name: 'Pieces', value: '18' }],
  },
];

/**
 * Approximate market multipliers applied to the GBP base price so each store's
 * catalogue looks locally plausible. These are illustrative, not exchange rates.
 */
export const MARKET_PRICE_MULTIPLIERS: Record<string, number> = {
  GBP: 1,
  USD: 1.32,
  EUR: 1.18,
  CAD: 1.78,
  AUD: 1.98,
  JPY: 198,
  SEK: 13.6,
  AED: 4.82,
  MXN: 23.4,
  SGD: 1.72,
};

export const CATEGORY_TREE: { name: string; children: string[] }[] = [
  { name: 'Kitchen', children: ['Small Appliances', 'Cookware', 'Cutlery', 'Coffee'] },
  { name: 'Living', children: ['Soft Furnishings', 'Lighting', 'Rugs'] },
  { name: 'Outdoor', children: ['Outerwear', 'Footwear', 'Packs', 'Shelter', 'Cooking', 'Accessories'] },
  { name: 'Workspace', children: ['Desks', 'Seating', 'Lighting', 'Storage', 'Accessories'] },
  { name: 'Services', children: ['Digital'] },
];
