/**
 * The integrations directory catalogue.
 *
 * Display-only in v1. No connector performs authentication, and none makes an
 * outbound request. Logos are rendered from a public icon CDN during local
 * development only — see docs/known-limitations.md.
 */
export interface SeedConnector {
  slug: string;
  name: string;
  vendor: string;
  category: string;
  shortDescription: string;
  longDescription: string;
  /** Simple Icons slug used to render the logo locally. */
  logoSlug: string;
  logoColor: string;
  docsUrl: string;
  status: 'AVAILABLE_FOR_CONFIGURATION' | 'COMING_SOON' | 'DISPLAY_ONLY' | 'PARTNER_MANAGED';
  integrationType: string;
  supportsMultiStore: boolean;
  tags: string[];
  sortOrder: number;
}

export const SEED_CONNECTORS: SeedConnector[] = [
  {
    slug: 'feedonomics',
    name: 'Feedonomics',
    vendor: 'BigCommerce',
    category: 'Data feeds',
    shortDescription: 'Product feed management and marketplace listing across hundreds of channels.',
    longDescription:
      'Transforms and syndicates catalogue data to advertising channels and marketplaces. In a multi-store estate it is usually configured per store hash, so this platform would hold one connector instance per connection.',
    logoSlug: 'bigcommerce',
    logoColor: '121118',
    docsUrl: 'https://feedonomics.com',
    status: 'COMING_SOON',
    integrationType: 'Managed service',
    supportsMultiStore: true,
    tags: ['feeds', 'marketplaces', 'advertising'],
    sortOrder: 10,
  },
  {
    slug: 'makeswift',
    name: 'Makeswift',
    vendor: 'BigCommerce',
    category: 'Content management',
    shortDescription: 'Visual page building for Catalyst storefronts.',
    longDescription:
      'A visual editor for composable BigCommerce storefronts. Page structures live in Makeswift rather than the BigCommerce content API, so content comparison between a Makeswift storefront and a Stencil storefront is not like-for-like.',
    logoSlug: 'bigcommerce',
    logoColor: '121118',
    docsUrl: 'https://www.makeswift.com',
    status: 'COMING_SOON',
    integrationType: 'Storefront',
    supportsMultiStore: true,
    tags: ['cms', 'catalyst', 'composable'],
    sortOrder: 20,
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    vendor: 'Stripe',
    category: 'Payments',
    shortDescription: 'Card, wallet and local payment-method processing.',
    longDescription:
      'Payment-gateway credentials are never read, written or copied by this platform. Gateway configuration remains a manual action inside each store’s control panel.',
    logoSlug: 'stripe',
    logoColor: '635BFF',
    docsUrl: 'https://stripe.com/docs',
    status: 'DISPLAY_ONLY',
    integrationType: 'Payment gateway',
    supportsMultiStore: false,
    tags: ['payments', 'gateway'],
    sortOrder: 30,
  },
  {
    slug: 'netsuite',
    name: 'Oracle NetSuite',
    vendor: 'Oracle',
    category: 'ERP',
    shortDescription: 'Financials, inventory and order management for the wider business.',
    longDescription:
      'Where NetSuite owns inventory, this platform switches the affected stores to the external-inventory strategy and reports quantities read-only rather than writing them.',
    logoSlug: 'oracle',
    logoColor: 'F80000',
    docsUrl: 'https://www.netsuite.com',
    status: 'COMING_SOON',
    integrationType: 'iPaaS-mediated',
    supportsMultiStore: true,
    tags: ['erp', 'inventory', 'finance'],
    sortOrder: 40,
  },
  {
    slug: 'dynamics-365',
    name: 'Microsoft Dynamics 365',
    vendor: 'Microsoft',
    category: 'ERP',
    shortDescription: 'Enterprise resource planning and commerce operations.',
    longDescription:
      'Typically integrated through an iPaaS layer. Customer and order data flow outward from BigCommerce; catalogue and pricing usually flow inward.',
    logoSlug: 'microsoft',
    logoColor: '5E5E5E',
    docsUrl: 'https://dynamics.microsoft.com',
    status: 'COMING_SOON',
    integrationType: 'iPaaS-mediated',
    supportsMultiStore: true,
    tags: ['erp', 'crm'],
    sortOrder: 50,
  },
  {
    slug: 'sap',
    name: 'SAP',
    vendor: 'SAP',
    category: 'ERP',
    shortDescription: 'Core ERP for finance, supply chain and master data.',
    longDescription:
      'In SAP-led estates the product master usually lives in SAP, which changes the inheritance model: BigCommerce stores become targets rather than sources.',
    logoSlug: 'sap',
    logoColor: '0FAAFF',
    docsUrl: 'https://www.sap.com',
    status: 'COMING_SOON',
    integrationType: 'iPaaS-mediated',
    supportsMultiStore: true,
    tags: ['erp', 'master data'],
    sortOrder: 60,
  },
  {
    slug: 'akeneo',
    name: 'Akeneo',
    vendor: 'Akeneo',
    category: 'PIM',
    shortDescription: 'Product information management and enrichment.',
    longDescription:
      'When a PIM is present it becomes the catalogue source of truth. This platform would then compare stores against the PIM export rather than against a master store.',
    logoSlug: 'akeneo',
    logoColor: '9B5DE5',
    docsUrl: 'https://www.akeneo.com',
    status: 'COMING_SOON',
    integrationType: 'API',
    supportsMultiStore: true,
    tags: ['pim', 'catalogue', 'localisation'],
    sortOrder: 70,
  },
  {
    slug: 'salsify',
    name: 'Salsify',
    vendor: 'Salsify',
    category: 'PIM',
    shortDescription: 'Product experience management and channel syndication.',
    longDescription:
      'Combines PIM with syndication. Overlaps with the catalogue-deployment workflow here, so the two must be scoped to avoid fighting over the same fields.',
    logoSlug: 'salsify',
    logoColor: '00A4E4',
    docsUrl: 'https://www.salsify.com',
    status: 'COMING_SOON',
    integrationType: 'API',
    supportsMultiStore: true,
    tags: ['pim', 'syndication'],
    sortOrder: 80,
  },
  {
    slug: 'pimcore',
    name: 'Pimcore',
    vendor: 'Pimcore',
    category: 'PIM',
    shortDescription: 'Open-source data and experience management platform.',
    longDescription:
      'Self-hosted PIM and DAM. Integration is bespoke, so the connector is documented rather than packaged.',
    logoSlug: 'pimcore',
    logoColor: '6428B4',
    docsUrl: 'https://pimcore.com',
    status: 'COMING_SOON',
    integrationType: 'API',
    supportsMultiStore: true,
    tags: ['pim', 'dam', 'open source'],
    sortOrder: 90,
  },
  {
    slug: 'celigo',
    name: 'Celigo',
    vendor: 'Celigo',
    category: 'iPaaS',
    shortDescription: 'Prebuilt integration flows between BigCommerce and back-office systems.',
    longDescription:
      'Provides managed flows for order, inventory and fulfilment sync. Where Celigo owns a flow, the matching capability here should be set to read-only to avoid two writers.',
    logoSlug: 'celigo',
    logoColor: '00A9E0',
    docsUrl: 'https://www.celigo.com',
    status: 'COMING_SOON',
    integrationType: 'iPaaS',
    supportsMultiStore: true,
    tags: ['ipaas', 'automation'],
    sortOrder: 100,
  },
  {
    slug: 'boomi',
    name: 'Boomi',
    vendor: 'Boomi',
    category: 'iPaaS',
    shortDescription: 'Enterprise integration platform for commerce and ERP data flows.',
    longDescription:
      'Commonly used to bridge BigCommerce with SAP or Oracle. Integration processes are defined in Boomi, not here.',
    logoSlug: 'boomi',
    logoColor: '00B2A9',
    docsUrl: 'https://boomi.com',
    status: 'COMING_SOON',
    integrationType: 'iPaaS',
    supportsMultiStore: true,
    tags: ['ipaas', 'enterprise'],
    sortOrder: 110,
  },
  {
    slug: 'workato',
    name: 'Workato',
    vendor: 'Workato',
    category: 'iPaaS',
    shortDescription: 'Recipe-based automation across commerce, finance and support systems.',
    longDescription:
      'Useful for approval routing and operational alerting. A future release could push this platform’s approval events into a Workato recipe.',
    logoSlug: 'workato',
    logoColor: 'FF6C37',
    docsUrl: 'https://www.workato.com',
    status: 'COMING_SOON',
    integrationType: 'iPaaS',
    supportsMultiStore: true,
    tags: ['ipaas', 'automation', 'workflow'],
    sortOrder: 120,
  },
  {
    slug: 'klaviyo',
    name: 'Klaviyo',
    vendor: 'Klaviyo',
    category: 'Marketing',
    shortDescription: 'Email and SMS marketing driven by store and customer events.',
    longDescription:
      'Operates per store. In a multi-store estate, take care that a customer present in two stores is not treated as one profile unless that is a deliberate, lawful choice.',
    logoSlug: 'klaviyo',
    logoColor: '000000',
    docsUrl: 'https://www.klaviyo.com',
    status: 'COMING_SOON',
    integrationType: 'API',
    supportsMultiStore: false,
    tags: ['email', 'sms', 'lifecycle'],
    sortOrder: 130,
  },
  {
    slug: 'hubspot',
    name: 'HubSpot',
    vendor: 'HubSpot',
    category: 'CRM',
    shortDescription: 'CRM, marketing automation and service desk.',
    longDescription:
      'Frequently the system of record for B2B accounts, which makes it relevant to the customer-group structure in the wholesale estate.',
    logoSlug: 'hubspot',
    logoColor: 'FF7A59',
    docsUrl: 'https://www.hubspot.com',
    status: 'COMING_SOON',
    integrationType: 'API',
    supportsMultiStore: false,
    tags: ['crm', 'marketing'],
    sortOrder: 140,
  },
  {
    slug: 'google-analytics',
    name: 'Google Analytics',
    vendor: 'Google',
    category: 'Analytics',
    shortDescription: 'Web and commerce analytics for each storefront.',
    longDescription:
      'Installed as a storefront script. Copying analytics scripts between stores is a known footgun — it double-counts traffic and can breach consent rules, so script deployment always warns.',
    logoSlug: 'googleanalytics',
    logoColor: 'E37400',
    docsUrl: 'https://analytics.google.com',
    status: 'DISPLAY_ONLY',
    integrationType: 'Storefront script',
    supportsMultiStore: false,
    tags: ['analytics', 'measurement'],
    sortOrder: 150,
  },
  {
    slug: 'segment',
    name: 'Segment',
    vendor: 'Twilio',
    category: 'Analytics',
    shortDescription: 'Customer data platform and event routing.',
    longDescription:
      'Routes storefront and server events to downstream tools. Source keys are per storefront, so each channel needs its own.',
    logoSlug: 'segment',
    logoColor: '52BD95',
    docsUrl: 'https://segment.com',
    status: 'COMING_SOON',
    integrationType: 'CDP',
    supportsMultiStore: true,
    tags: ['cdp', 'events'],
    sortOrder: 160,
  },
  {
    slug: 'avalara',
    name: 'Avalara',
    vendor: 'Avalara',
    category: 'Tax',
    shortDescription: 'Automated sales-tax and VAT calculation.',
    longDescription:
      'Where Avalara is active, BigCommerce is not the source of truth for tax. This platform then reports tax configuration read-only and never copies rates between stores.',
    logoSlug: 'avalara',
    logoColor: 'FF8B00',
    docsUrl: 'https://www.avalara.com',
    status: 'COMING_SOON',
    integrationType: 'Tax provider',
    supportsMultiStore: true,
    tags: ['tax', 'compliance'],
    sortOrder: 170,
  },
  {
    slug: 'vertex',
    name: 'Vertex',
    vendor: 'Vertex',
    category: 'Tax',
    shortDescription: 'Enterprise tax determination and compliance.',
    longDescription:
      'Common in large multi-jurisdiction estates. Same rule as Avalara: tax stays read-only here.',
    logoSlug: 'vertex',
    logoColor: '2A2A2A',
    docsUrl: 'https://www.vertexinc.com',
    status: 'COMING_SOON',
    integrationType: 'Tax provider',
    supportsMultiStore: true,
    tags: ['tax', 'compliance'],
    sortOrder: 180,
  },
  {
    slug: 'shipstation',
    name: 'ShipStation',
    vendor: 'ShipStation',
    category: 'Shipping',
    shortDescription: 'Multi-carrier fulfilment and label printing.',
    longDescription:
      'Owns fulfilment once an order is placed. Order-status writes from this platform are disabled partly to avoid conflicting with a fulfilment system.',
    logoSlug: 'shipstation',
    logoColor: '3A3A3A',
    docsUrl: 'https://www.shipstation.com',
    status: 'COMING_SOON',
    integrationType: 'API',
    supportsMultiStore: true,
    tags: ['shipping', 'fulfilment'],
    sortOrder: 190,
  },
  {
    slug: 'shipperhq',
    name: 'ShipperHQ',
    vendor: 'ShipperHQ',
    category: 'Shipping',
    shortDescription: 'Advanced shipping rates and delivery-date rules at checkout.',
    longDescription:
      'Shipping rules configured in ShipperHQ are not visible through the BigCommerce shipping API, so shipping comparison is incomplete for stores that use it.',
    logoSlug: 'shipperhq',
    logoColor: '00A0DF',
    docsUrl: 'https://shipperhq.com',
    status: 'COMING_SOON',
    integrationType: 'Checkout',
    supportsMultiStore: true,
    tags: ['shipping', 'checkout'],
    sortOrder: 200,
  },
  {
    slug: 'algolia',
    name: 'Algolia',
    vendor: 'Algolia',
    category: 'Search',
    shortDescription: 'Hosted search and product discovery.',
    longDescription:
      'Each storefront needs its own index. Catalogue deployments should be followed by a re-index, which is tracked as a post-deployment task.',
    logoSlug: 'algolia',
    logoColor: '003DFF',
    docsUrl: 'https://www.algolia.com',
    status: 'COMING_SOON',
    integrationType: 'Search',
    supportsMultiStore: true,
    tags: ['search', 'discovery'],
    sortOrder: 210,
  },
  {
    slug: 'zendesk',
    name: 'Zendesk',
    vendor: 'Zendesk',
    category: 'Customer service',
    shortDescription: 'Support ticketing with order context.',
    longDescription:
      'Agents need order lookups across several stores, which is one of the reasons the unified order view exists.',
    logoSlug: 'zendesk',
    logoColor: '03363D',
    docsUrl: 'https://www.zendesk.com',
    status: 'COMING_SOON',
    integrationType: 'API',
    supportsMultiStore: true,
    tags: ['support', 'service'],
    sortOrder: 220,
  },
  {
    slug: 'dynamic-yield',
    name: 'Dynamic Yield',
    vendor: 'Mastercard',
    category: 'Personalisation',
    shortDescription: 'On-site personalisation and experimentation.',
    longDescription:
      'Personalisation campaigns are storefront-specific and are not represented in the BigCommerce content APIs.',
    logoSlug: 'mastercard',
    logoColor: 'EB001B',
    docsUrl: 'https://www.dynamicyield.com',
    status: 'COMING_SOON',
    integrationType: 'Storefront script',
    supportsMultiStore: false,
    tags: ['personalisation', 'testing'],
    sortOrder: 230,
  },
  {
    slug: 'brightpearl',
    name: 'Brightpearl',
    vendor: 'Sage',
    category: 'OMS',
    shortDescription: 'Retail operations, order and inventory management.',
    longDescription:
      'A common OMS for mid-market multi-store retailers. Where it is present, inventory writes from this platform stay disabled.',
    logoSlug: 'sage',
    logoColor: '00D639',
    docsUrl: 'https://www.brightpearl.com',
    status: 'COMING_SOON',
    integrationType: 'API',
    supportsMultiStore: true,
    tags: ['oms', 'inventory'],
    sortOrder: 240,
  },
];
